import type { Component } from "../types"

/**
 * Terms of Service page with static legal content.
 */
export default function createTermsPage(): Component {
  const container = document.createElement("div")
  container.className = "min-h-screen pt-20 pb-16 px-6"
  container.innerHTML = `
    <div class="max-w-4xl mx-auto prose prose-slate dark:prose-invert">
      <h1>Qcut – Terms of Service</h1>

      <p><strong>Last Updated:</strong> January 2026</p>

      <h2>1. Acceptance of Terms</h2>
      <p>These Terms of Service ("Terms") govern your access to and use of <strong>Qcut</strong> ("Service"), provided by <a href="https://www.editonthespot.com/">Edit on the Spot</a> ("we," "us," or "our"), website: www.editonthespot.com.</p>
      <p>By accessing or using Qcut, you agree to be bound by these Terms and our <strong>Privacy Policy</strong>. If you do not agree, do not use the Service.</p>
      <p>We may update these Terms at any time by posting a revised version on our website. The "Last Updated" date above reflects the latest revision. Your continued use of Qcut after any update constitutes acceptance of the new Terms.</p>

      <h2>2. Description of Services</h2>
      <p>Qcut is a cloud-based and browser-based video editing platform that allows users to upload, edit, and export media content using automated and AI-assisted tools. The Service may include:</p>
      <ul>
        <li>Video upload, editing, and export functions;</li>
        <li>AI-powered automation tools;</li>
        <li>Browser-based and server-side processing; and</li>
        <li>Optional integration with third-party services (e.g., cloud storage).</li>
      </ul>

      <h2>3. Global Access and Compliance</h2>
      <p>Qcut operates globally and is accessible from multiple jurisdictions. By using the Service, you represent that you will comply with all applicable laws and regulations in your location.</p>
      <p>Qcut reserves the right to restrict or terminate access in any region where the Service may violate local laws or regulations.</p>

      <h2>4. Licence to Use</h2>
      <p>Subject to these Terms, Qcut grants you a limited, non-exclusive, non-transferable, revocable licence to access and use the Service for personal or authorised business purposes.</p>
      <p>You may not:</p>
      <ul>
        <li>Copy, modify, distribute, or create derivative works of the Service;</li>
        <li>Reverse-engineer, decompile, or extract source code or AI model weights;</li>
        <li>Remove or alter any copyright or proprietary notices;</li>
        <li>Access the Service through automated means (bots, scrapers, or scripts); or</li>
        <li>Use the Service to build or train competing AI or editing products.</li>
      </ul>

      <h2>5. AI Services</h2>
      <p>Qcut includes AI-assisted features. You agree not to:</p>
      <ul>
        <li>Attempt to discover or extract the underlying algorithms, weights, or systems;</li>
        <li>Use automated data extraction or scraping methods;</li>
        <li>Use Qcut or data generated by Qcut to train or improve another AI system;</li>
        <li>Generate, upload, or distribute harmful, defamatory, or infringing content using AI features.</li>
      </ul>
      <p>Qcut may process and temporarily store user inputs and outputs to monitor system performance, prevent misuse, and enhance service quality. Qcut does not sell or share your personal or creative data with third parties.</p>

      <h2>6. User Content and Ownership</h2>
      <p>6.1. You retain ownership of all video, audio, and creative material you upload, edit, or generate through Qcut ("User Content").</p>
      <p>By using the Service, you grant Qcut a <strong>worldwide, royalty-free, non-exclusive licence</strong> to:</p>
      <ul>
        <li>Process and display your content to operate the platform;</li>
        <li>Use anonymised data to improve service performance and AI features; and</li>
        <li>Temporarily store your content for technical and operational reasons.</li>
      </ul>
      <p>You confirm that you own all necessary rights to your content and that it does not infringe any third-party intellectual property or privacy rights.</p>
      <p>6.2. Your Content is your sole responsibility. Qcut does not guarantee the retention, backup, or recoverability of any content, project, or file created or uploaded through the Service.</p>
      <p>You are solely responsible for downloading and securely storing copies of your completed videos or any other materials you wish to keep. Qcut is not liable for any loss of data, edits, or projects arising from:</p>
      <ul>
        <li>Browser or device failure,</li>
        <li>Session timeouts or accidental closure, or</li>
        <li>Network interruptions or user error.</li>
      </ul>

      <h2>7. Intellectual Property</h2>
      <p>All software, design, features, and branding of Qcut are owned by <a href="https://www.editonthespot.com/">Edit on the Spot</a> or its licensors. You are not granted ownership rights or any implied licences except as expressly stated.</p>
      <p>You may not use Qcut's trademarks, trade names, or branding without prior written consent.</p>

      <h2>8. Links to Third-Party Sites</h2>
      <p>The Qcut website and platform may contain links to third-party websites, services, or resources ("Linked Sites"). These links are provided solely for convenience and informational purposes.</p>
      <p>Qcut and <a href="https://www.editonthespot.com/">Edit on the Spot</a> do not control, endorse, or assume responsibility for the content, availability, accuracy, policies, or practices of any Linked Site.</p>
      <ul>
        <li>Qcut is not responsible for any loss, damage, or harm arising from your use of or reliance on Linked Sites;</li>
        <li>The inclusion of any link does not imply endorsement or affiliation by Qcut; and</li>
        <li>You access and use Linked Sites entirely at your own risk.</li>
      </ul>

      <h2>9. Privacy and Data Protection</h2>
      <p>Your use of Qcut is governed by our <strong>Privacy Policy</strong>, which complies with the <strong>Australian Privacy Act 1988 (Cth)</strong>, <strong>GDPR (EU/UK)</strong>, and <strong>CCPA (US)</strong> where applicable.</p>
      <p>Qcut minimises personal data collection and primarily processes your content locally or in secure cloud environments. We do not sell or share personal information with advertisers.</p>
      <p>Users from the EU, UK, and California have the right to request deletion, access, or correction of their data by contacting: <a href="mailto:support@editonthespot.com">support@editonthespot.com</a></p>

      <h2>10. No Unlawful or Prohibited Use</h2>
      <p>You agree not to use Qcut for any unlawful purpose or in any way that could damage, disable, or impair the Service.</p>
      <p>You must not upload, distribute, or create content that:</p>
      <ul>
        <li>Infringes copyright, trademark, or privacy rights;</li>
        <li>Contains malware or malicious code;</li>
        <li>Defames, harasses, or discriminates;</li>
        <li>Promotes illegal activity.</li>
      </ul>
      <p>We reserve the right to suspend or terminate access for violations of these Terms.</p>

      <h2>11. Warranty Disclaimer</h2>
      <p>Qcut is provided <strong>"as is" and "as available."</strong></p>
      <p>We make no warranties or guarantees, express or implied, including:</p>
      <ul>
        <li>Accuracy or reliability of results;</li>
        <li>Uninterrupted operation or error-free performance;</li>
        <li>Compatibility with your device or browser;</li>
        <li>Preservation of data or content beyond your session.</li>
      </ul>
      <p>Your use of Qcut is at your own risk.</p>

      <h2>12. Limitation of Liability</h2>
      <p>To the fullest extent permitted by applicable law, <a href="https://www.editonthespot.com/">Edit on the Spot</a> <strong>and its affiliates shall not be liable</strong> for any:</p>
      <ul>
        <li>Indirect, incidental, or consequential damages;</li>
        <li>Loss of data, revenue, or profits; or</li>
        <li>Business interruption or system failure.</li>
      </ul>
      <p>In jurisdictions where liability cannot be fully excluded, Qcut's liability will be limited to the minimum amount required by law.</p>

      <h2>13. Indemnification</h2>
      <p>You agree to indemnify and hold harmless Edit on the Spot, its directors, officers, employees, and agents from any claim arising from:</p>
      <ul>
        <li>Your use of the Service;</li>
        <li>Your content or data; or</li>
        <li>Your breach of these Terms or applicable law.</li>
      </ul>

      <h2>14. Termination</h2>
      <p>Qcut may suspend or terminate access without notice if you:</p>
      <ul>
        <li>Breach these Terms;</li>
        <li>Engage in unlawful or harmful activity; or</li>
        <li>Interfere with the Service's operation.</li>
      </ul>
      <p>You may cease use of Qcut at any time. Termination does not affect accrued rights or ongoing confidentiality obligations.</p>

      <h2>15. Compliance with Applicable Laws</h2>
      <p>Qcut operates globally and complies with applicable data protection, consumer, and digital services laws in the regions where the Service is available.</p>
      <p>Nothing in these Terms limits any legal rights you may have under the laws of your country of residence.</p>

      <h2>16. General Provisions</h2>
      <ul>
        <li><strong>Entire Agreement:</strong> These Terms constitute the complete agreement between you and Qcut.</li>
        <li><strong>Severability:</strong> If any part is found unenforceable, the remainder remains valid.</li>
        <li><strong>Assignment:</strong> Qcut may assign its rights under these Terms to an affiliate or successor.</li>
        <li><strong>Language:</strong> These Terms are provided in English; translations are for convenience only.</li>
        <li><strong>Modifications:</strong> Qcut may update these Terms periodically; continued use constitutes acceptance.</li>
      </ul>

      <h2>17. Contact Information</h2>
      <p><strong>Qcut</strong> (operated by <a href="https://www.editonthespot.com/">Edit on the Spot</a>)</p>
      <p>
        Email: <a href="mailto:support@editonthespot.com">support@editonthespot.com</a><br />
        Website: <a href="https://qcut.app">qcut.app</a>
      </p>
    </div>
  `
  return { element: container, destroy: () => {} }
}
